### PR TITLE
Added question 5 basic layout

### PR DESCRIPTION
**Pull request by alvinbengeorge**
Please check and change, there might be some bloat in there, double check and you can edit it, plus check if its done

### CODE REVIEW

**Comment by alvinbengeorge** [comment]
Oh no
its ok you can close this, take Sidhant's

**Comment by sidhant-sriv** [comment]
You can close it yourself iirc

**Comment by alvinbengeorge** [comment]
all right

**Comment by sidhant-sriv** [comment]
I recommend closing this PR since there will be a merge error otherwise.
I have fixed the issue in my PR

**Comment by alvinbengeorge** [comment]
all right cool

**Pull request closed without merging**
