### PR TITLE
Problem 1,2 and 5

### PR DESCRIPTION
**Pull request by sidhant-sriv**

### CODE REVIEW

**Review by alvinbengeorge — COMMENTED** [review]
There's a problem here
use len() function here, also you might need default values for this
image

Edit: This is for Question 5 binary search

**Comment by sidhant-sriv** [comment]
> There's a problem here
> use len() function here, also you might need default values for this
> image

Where is the problem?

**Comment by alvinbengeorge** [comment]
I accidentally opened a request
Yes its very long lol, but check that out
 
 Also sorting after entry

**Comment by alvinbengeorge** [comment]
Sidhant use .sort() for binary_search_main arr
or else its not sorted

**Pull request merged**
